// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

import (
	"time"
)

type AuthPayload struct {
	User *User `json:"user"`
}

type Commit struct {
	Hash    string    `json:"hash"`
	Message string    `json:"message"`
	Author  string    `json:"author"`
	Date    time.Time `json:"date"`
}

type File struct {
	Path     string  `json:"path"`
	Content  *string `json:"content,omitempty"`
	Size     int     `json:"size"`
	IsTooBig bool    `json:"isTooBig"`
	IsBinary bool    `json:"isBinary"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
