package server

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"errors"
	"io"
	"log/slog"
	"os"
	"time"

	"github.com/google/uuid"
	"github.com/lewtec/superfolha/internal/apierrors"
	"github.com/lewtec/superfolha/internal/auth"
	"github.com/lewtec/superfolha/internal/db"
	"github.com/lewtec/superfolha/internal/project"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (*AuthPayload, error) {
	authResp, err := r.authService.Register(ctx, email, password)
	if err != nil {
		return nil, err
	}
	return authPayloadFromResponse(ctx, authResp, "Register")
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*AuthPayload, error) {
	authResp, err := r.authService.Login(ctx, email, password)
	if err != nil {
		return nil, err
	}
	return authPayloadFromResponse(ctx, authResp, "Login")
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, name string) (*Project, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	projectUUID, err := uuid.NewV7()
	if err != nil {
		return nil, apierrors.Internal(err)
	}
	projectID := projectUUID.String()
	projectPath := r.projectService.GetProjectPath(projectID)

	dbProject, err := r.Repo.CreateProject(ctx, db.CreateProjectParams{
		ID:      projectID,
		UserID:  user.UserID,
		Name:    name,
		GitPath: projectPath,
	})
	if err != nil {
		return nil, apierrors.Internal(err)
	}

	return toGraphQLProject(dbProject), nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	project, projectPath, _, err := r.getAndCheckProject(ctx, id)
	if err != nil {
		return false, err
	}

	// Tear down live collab before wiping the repo so flush/commit/idle-evict
	// cannot write back into (or recreate) a deleted project path.
	if r.hubs != nil {
		r.hubs.CloseProject(project.ID)
	}

	if err := r.Repo.DeleteProject(ctx, project.ID); err != nil {
		return false, apierrors.Internal(err)
	}

	if err := os.RemoveAll(projectPath); err != nil {
		return false, apierrors.Internal(err)
	}

	return true, nil
}

// SaveFile is the resolver for the saveFile field.
func (r *mutationResolver) SaveFile(ctx context.Context, projectID string, path string, content string) (*File, error) {
	_, _, _, err := r.getAndCheckProject(ctx, projectID)
	if err != nil {
		return nil, err
	}

	// Live hub updates CRDT + disk; otherwise disk only. Mirror DeleteFile routing.
	var saveErr error
	if r.hubs != nil {
		if hub := r.hubs.GetIfLive(projectID); hub != nil {
			saveErr = hub.SaveTextFile(path, content)
		} else {
			saveErr = r.projectService.SaveFile(projectID, path, content)
		}
	} else {
		saveErr = r.projectService.SaveFile(projectID, path, content)
	}
	if saveErr != nil {
		if errors.Is(saveErr, project.ErrInvalidPath) {
			return nil, apierrors.New(apierrors.CodeInvalidInput, "invalid file path")
		}
		return nil, apierrors.Internal(saveErr)
	}

	contentPtr := &content
	isBinary := HasBinary([]byte(content), path)
	return &File{
		Path:     path,
		Content:  contentPtr,
		Size:     len(content),
		IsTooBig: len(content) > MaxGraphQLFileSize,
		IsBinary: isBinary,
	}, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, projectID string, path string) (bool, error) {
	_, _, _, err := r.getAndCheckProject(ctx, projectID)
	if err != nil {
		return false, err
	}

	var delErr error
	if r.hubs != nil {
		if hub := r.hubs.GetIfLive(projectID); hub != nil {
			delErr = hub.DeleteFile(path)
		} else {
			delErr = r.projectService.DeleteFile(projectID, path)
		}
	} else {
		delErr = r.projectService.DeleteFile(projectID, path)
	}
	if delErr != nil {
		if errors.Is(delErr, project.ErrInvalidPath) {
			return false, apierrors.New(apierrors.CodeInvalidInput, "invalid file path")
		}
		if errors.Is(delErr, os.ErrNotExist) {
			return false, apierrors.New(apierrors.CodeFileNotFound, "file not found")
		}
		return false, apierrors.Internal(delErr)
	}

	return true, nil
}

// Commit is the resolver for the commit field.
func (r *mutationResolver) Commit(ctx context.Context, projectID string, message string) (*Commit, error) {
	project, _, user, err := r.getAndCheckProject(ctx, projectID)
	if err != nil {
		return nil, err
	}

	// Live hub: flush + lock + commit through common path.
	if r.hubs != nil {
		if hub := r.hubs.GetIfLive(projectID); hub != nil {
			hash, err := hub.Commit(message, user.Email)
			if err != nil {
				return nil, apierrors.Internal(err)
			}
			if err := r.Repo.UpdateProjectTimestamp(ctx, project.ID); err != nil {
				slog.Warn("failed to update project timestamp", "project_id", project.ID, "err", err)
			}
			return &Commit{
				Hash:    hash,
				Message: message,
				Author:  user.Email,
				Date:    time.Now(),
			}, nil
		}
	}

	commit, err := r.projectService.CommitChanges(projectID, user.Email, message)
	if err != nil {
		return nil, apierrors.Internal(err)
	}

	if err := r.Repo.UpdateProjectTimestamp(ctx, project.ID); err != nil {
		slog.Warn("failed to update project timestamp", "project_id", project.ID, "err", err)
	}

	return toGraphQLCommit(commit), nil
}

// Files is the resolver for the files field.
func (r *projectResolver) Files(ctx context.Context, obj *Project) ([]*File, error) {
	gitFiles, err := r.projectService.ListFiles(obj.ID)
	if err != nil {
		return nil, apierrors.Internal(err)
	}

	files := make([]*File, len(gitFiles))
	for i, f := range gitFiles {
		isTooBig := f.Size > MaxGraphQLFileSize

		fileReader, _, err := r.projectService.ReadFile(obj.ID, f.Path)
		if err != nil {
			return nil, apierrors.Internal(err)
		}

		var buf [512]byte
		n, err := io.ReadFull(fileReader, buf[:])
		if err != nil && !errors.Is(err, io.EOF) && !errors.Is(err, io.ErrUnexpectedEOF) {
			fileReader.Close()
			return nil, apierrors.Internal(err)
		}
		isBinary := HasBinary(buf[:n], f.Path)
		fileReader.Close()

		files[i] = &File{
			Path:     f.Path,
			Content:  nil,
			Size:     int(f.Size),
			IsTooBig: isTooBig,
			IsBinary: isBinary,
		}
	}

	return files, nil
}

// File is the resolver for the file field.
func (r *projectResolver) File(ctx context.Context, obj *Project, path string) (*File, error) {
	fileReader, fileSize, err := r.projectService.ReadFile(obj.ID, path)
	if err != nil {
		if errors.Is(err, project.ErrFileNotFound) {
			return nil, apierrors.New(apierrors.CodeFileNotFound, "file not found")
		}
		if errors.Is(err, project.ErrInvalidPath) {
			return nil, apierrors.New(apierrors.CodeInvalidInput, "invalid file path")
		}
		return nil, apierrors.Internal(err)
	}
	defer fileReader.Close()

	isTooBig := fileSize > MaxGraphQLFileSize
	var content *string

	var buf [512]byte
	n, err := io.ReadFull(fileReader, buf[:])
	if err != nil && !errors.Is(err, io.EOF) && !errors.Is(err, io.ErrUnexpectedEOF) {
		return nil, apierrors.Internal(err)
	}
	isBinary := HasBinary(buf[:n], path)

	if seeker, ok := fileReader.(io.ReadSeeker); ok {
		if _, err := seeker.Seek(0, io.SeekStart); err != nil {
			return nil, apierrors.Internal(err)
		}
	} else {
		slog.Warn("fileReader is not seekable", "path", path)
	}

	if !isTooBig && !isBinary {
		contentBytes, err := io.ReadAll(fileReader)
		if err != nil {
			return nil, apierrors.Internal(err)
		}
		c := string(contentBytes)
		content = &c
	}

	return &File{
		Path:     path,
		Content:  content,
		Size:     int(fileSize),
		IsTooBig: isTooBig,
		IsBinary: isBinary,
	}, nil
}

// History is the resolver for the history field.
func (r *projectResolver) History(ctx context.Context, obj *Project) ([]*Commit, error) {
	gitCommits, err := r.projectService.GetHistory(obj.ID)
	if err != nil {
		return nil, apierrors.Internal(err)
	}

	commits := make([]*Commit, len(gitCommits))
	for i, c := range gitCommits {
		commits[i] = toGraphQLCommit(c)
	}

	return commits, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	user, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, nil
	}

	if _, err := uuid.Parse(user.UserID); err != nil {
		return nil, apierrors.New(apierrors.CodeInvalidInput, "invalid user ID")
	}

	dbUser, err := r.Repo.GetUserByID(ctx, user.UserID)
	if err != nil {
		return nil, apierrors.New(apierrors.CodeNotFound, "user not found")
	}

	return toGraphQLUser(dbUser.ID, dbUser.Email), nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*Project, error) {
	user, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}

	dbProjects, err := r.Repo.GetUserProjects(ctx, user.UserID)
	if err != nil {
		return nil, apierrors.Internal(err)
	}

	projects := make([]*Project, len(dbProjects))
	for i, p := range dbProjects {
		projects[i] = toGraphQLProject(p)
	}

	return projects, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*Project, error) {
	project, _, _, err := r.getAndCheckProject(ctx, id)
	if err != nil {
		return nil, err
	}

	return toGraphQLProject(*project), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Project returns ProjectResolver implementation.
func (r *Resolver) Project() ProjectResolver { return &projectResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type projectResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
