// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Document(c Chrome) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(c.Lang)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/layout/document.templ`, Line: 5, Col: 20}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-theme=\"superfolha\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if c.Title != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<title>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(c.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/layout/document.templ`, Line: 10, Col: 20}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " · Superfolha</title>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<title>Superfolha</title>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<link rel=\"icon\" href=\"/static/brand/favicon.png\" type=\"image/png\"><script>\n\t\t\t\t(function () {\n\t\t\t\t\tvar KEY = \"theme\";\n\t\t\t\t\tfunction pref() {\n\t\t\t\t\t\tvar raw = localStorage.getItem(KEY);\n\t\t\t\t\t\tif (raw === \"light\" || raw === \"dark\") return raw;\n\t\t\t\t\t\tif (raw === \"superfolha-dark\" || raw === \"dark\") return \"dark\";\n\t\t\t\t\t\tif (raw === \"superfolha\" || raw === \"light\") return \"light\";\n\t\t\t\t\t\treturn \"system\";\n\t\t\t\t\t}\n\t\t\t\t\tfunction resolve(p) {\n\t\t\t\t\t\tif (p === \"dark\") return \"superfolha-dark\";\n\t\t\t\t\t\tif (p === \"light\") return \"superfolha\";\n\t\t\t\t\t\treturn window.matchMedia(\"(prefers-color-scheme: dark)\").matches\n\t\t\t\t\t\t\t? \"superfolha-dark\"\n\t\t\t\t\t\t\t: \"superfolha\";\n\t\t\t\t\t}\n\t\t\t\t\tfunction apply(name) {\n\t\t\t\t\t\tdocument.documentElement.setAttribute(\"data-theme\", name);\n\t\t\t\t\t}\n\t\t\t\t\twindow.__sfTheme = {\n\t\t\t\t\t\tresolve: function () { return resolve(pref()); },\n\t\t\t\t\t\ttoggle: function () {\n\t\t\t\t\t\t\tvar dark = resolve(pref()) === \"superfolha-dark\";\n\t\t\t\t\t\t\tvar next = dark ? \"light\" : \"dark\";\n\t\t\t\t\t\t\tlocalStorage.setItem(KEY, next);\n\t\t\t\t\t\t\tapply(resolve(next));\n\t\t\t\t\t\t\treturn next;\n\t\t\t\t\t\t},\n\t\t\t\t\t\tapply: apply\n\t\t\t\t\t};\n\t\t\t\t\tapply(resolve(pref()));\n\t\t\t\t})();\n\t\t\t</script><link href=\"/static/style.css\" rel=\"stylesheet\" type=\"text/css\"></head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
