// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
)

type Project struct {
	ID        string         `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	Name      string         `json:"name"`
	GitPath   string         `json:"git_path"`
	CreatedAt sql.NullString `json:"created_at"`
	UpdatedAt sql.NullString `json:"updated_at"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	CreatedAt    sql.NullString `json:"created_at"`
}
