// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
)

type Project struct {
	ID        string
	UserID    sql.NullString
	Name      string
	GitPath   string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullString
}
