// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProject(ctx context.Context, id string) error
	GetProject(ctx context.Context, id string) (Project, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserProjects(ctx context.Context, userID sql.NullString) ([]Project, error)
	UpdateProjectTimestamp(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
