// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserWithID(ctx context.Context, arg CreateUserWithIDParams) (User, error)
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserProjects(ctx context.Context, userID pgtype.UUID) ([]Project, error)
	UpdateProjectTimestamp(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
