// Code generated by lewkit generate db. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	db "github.com/lewtec/lewkit/x/db"
	_ "github.com/lewtec/lewkit/x/db/sqlite"
	sqlite "github.com/lewtec/superfolha/internal/db/sqlite"
)

type CreateProjectParams struct {
	ID      string
	UserID  sql.NullString
	Name    string
	GitPath string
}
type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
}
type Project struct {
	ID        string
	UserID    sql.NullString
	Name      string
	GitPath   string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}
type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullString
}
type Queries interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProject(ctx context.Context, id string) error
	GetProject(ctx context.Context, id string) (Project, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserProjects(ctx context.Context, userID sql.NullString) ([]Project, error)
	UpdateProjectTimestamp(ctx context.Context, id string) error
}
type sqliteWrap struct {
	q *sqlite.Queries
}

func (w sqliteWrap) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	v, err := w.q.CreateProject(ctx, sqlite.CreateProjectParams(arg))
	return Project(v), err
}
func (w sqliteWrap) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	v, err := w.q.CreateUser(ctx, sqlite.CreateUserParams(arg))
	return User(v), err
}
func (w sqliteWrap) DeleteProject(ctx context.Context, id string) error {
	return w.q.DeleteProject(ctx, id)
}
func (w sqliteWrap) GetProject(ctx context.Context, id string) (Project, error) {
	v, err := w.q.GetProject(ctx, id)
	return Project(v), err
}
func (w sqliteWrap) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	v, err := w.q.GetUserByEmail(ctx, lower)
	return User(v), err
}
func (w sqliteWrap) GetUserByID(ctx context.Context, id string) (User, error) {
	v, err := w.q.GetUserByID(ctx, id)
	return User(v), err
}
func (w sqliteWrap) GetUserProjects(ctx context.Context, userID sql.NullString) ([]Project, error) {
	v, err := w.q.GetUserProjects(ctx, userID)
	out := make([]Project, len(v))
	for i := range v {
		out[i] = Project(v[i])
	}
	return out, err
}
func (w sqliteWrap) UpdateProjectTimestamp(ctx context.Context, id string) error {
	return w.q.UpdateProjectTimestamp(ctx, id)
}
func New(url string) func(db.DBTX) Queries {
	return func(tx db.DBTX) Queries {
		switch db.Scheme(url) {
		case "sqlite":
			return sqliteWrap{q: sqlite.New(tx)}
		default:
			return nil
		}
	}
}

type DBArg struct {
	db.Arg[Queries]
}

func (a *DBArg) Open(ctx context.Context) error {
	c := a.Value()
	if c == nil {
		return fmt.Errorf("database url not set")
	}
	return a.Arg.Open(ctx, FS, New(c.URL()))
}
